package com.example.a210819_fauzan_mrnelson_project1

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import com.example.a210819_fauzan_mrnelson_project1.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddLogScreen(navController: NavHostController, viewModel: SolarViewModel) {

    // Form state - local to this screen
    var date by remember { mutableStateOf("") }
    var solarGenerated by remember { mutableStateOf("") }
    var energyUsed by remember { mutableStateOf("") }
    var notes by remember { mutableStateOf("") }

    // Error state
    var showError by remember { mutableStateOf(false) }
    var successMessage by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("➕ Add Energy Log") },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = TextWhite)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = PrimaryGreen,
                    titleContentColor = TextWhite
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .background(MaterialTheme.colorScheme.background)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {

            // Info card
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = LightGreen.copy(alpha = 0.15f))
            ) {
                Text(
                    "📋 Record your daily solar energy data here. " +
                            "This log will be saved and visible in the Log List screen.",
                    modifier = Modifier.padding(14.dp),
                    style = MaterialTheme.typography.bodyMedium,
                    color = DarkGreen
                )
            }

            // Date field
            OutlinedTextField(
                value = date,
                onValueChange = { date = it },
                label = { Text("Date (e.g. 10/05/2025)") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true
            )

            // Solar Generated field
            OutlinedTextField(
                value = solarGenerated,
                onValueChange = { solarGenerated = it },
                label = { Text("Solar Generated (kWh)") },
                modifier = Modifier.fillMaxWidth(),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                singleLine = true
            )

            // Energy Used field
            OutlinedTextField(
                value = energyUsed,
                onValueChange = { energyUsed = it },
                label = { Text("Energy Used (kWh)") },
                modifier = Modifier.fillMaxWidth(),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                singleLine = true
            )

            // Notes field
            OutlinedTextField(
                value = notes,
                onValueChange = { notes = it },
                label = { Text("Notes (optional)") },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(120.dp),
                maxLines = 4
            )

            // Error message
            if (showError) {
                Text(
                    "⚠️ Please fill in Date, Solar Generated, and Energy Used.",
                    color = MaterialTheme.colorScheme.error,
                    style = MaterialTheme.typography.bodySmall
                )
            }

            // Success message
            if (successMessage) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = LightGreen.copy(alpha = 0.3f))
                ) {
                    Text(
                        "✅ Log added successfully!",
                        modifier = Modifier.padding(12.dp),
                        color = DarkGreen
                    )
                }
            }

            // Submit Button
            Button(
                onClick = {
                    // Validate input
                    if (date.isBlank() || solarGenerated.isBlank() || energyUsed.isBlank()) {
                        showError = true
                        successMessage = false
                    } else {
                        // ADD item to ViewModel - this is the shared state!
                        viewModel.addEnergyLog(
                            date = date,
                            solarGenerated = "$solarGenerated kWh",
                            energyUsed = "$energyUsed kWh",
                            notes = notes
                        )

                        // Reset form
                        date = ""
                        solarGenerated = ""
                        energyUsed = ""
                        notes = ""
                        showError = false
                        successMessage = true
                    }
                },
                modifier = Modifier.fillMaxWidth(),
                colors = ButtonDefaults.buttonColors(containerColor = PrimaryGreen)
            ) {
                Text("💾 Save Log", color = TextWhite)
            }

            // Navigate to Log List button
            OutlinedButton(
                onClick = { navController.navigate("log_list") },
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("📋 View All Logs")
            }
        }
    }
}